### PR TITLE
Add notebook for inference on unemployment claims time series

### PR DESCRIPTION
**Pull request by neerajprad**
**TODOs:**

 - [x] Inference is currently slow (needs a few minutes even for autoguides on 400 odd data points) - Is it possible to vectorize the SGT model? EDIT - This is partially vectorizable on a seasonality window.
 - [ ] Run HMC on this - might be too slow on the non-vectorized model.
 - [ ] Get the global trend to be correctly inferred.
 - [ ] Add more description, and explain intermediate steps.

### CODE REVIEW

**Comment by fehiepsi** [comment]
@neerajprad I think for this data, the global linear decreasing trend is clear so you can put a negative prior for `gamma` (kind of `gamma` -> `-new_gamma`, `new_gamma ~ HalfNormal(1)` and change prior for `pow_trend` so that it puts more weights around 0 (for linear effect).

**Comment by neerajprad** [comment]
Thanks @fehiepsi. Yes, I'll make those changes to see if we can get a better infer the global trend.

**Comment by neerajprad** [comment]
@fritzo, @martinjankowiak - I have added a partially vectorized (over the seasonality window) version of SGT to the [second notebook](https://nbviewer.jupyter.org/github/pyro-ppl/sandbox/blob/b616ddf47d8435781d56a857b313e48ff05da877/2019-08-time-series/part%20ii%20-%20Inference.ipynb), which is much faster than the earlier version. There are a few small issues that I am working on like improving the global trend detection.

While the basic algorithm is quite simple, there are a few subtleties involved in coding it up, and the resulting code is a bit involved. Let me know if there are any alternative (non-sequential pyronic) models that will be good to try on this dataset.

**Comment by fehiepsi** [comment]
> added a partially vectorized (over the seasonality window)

This is super neat! Love this! (your method reminds me the time I tried to vectorize the non-trivial LKJ transform, which seems not possible at the first look, but later turned out to be possible and be much faster than using for-loop)

**Comment by fritzo** [comment]
nit: could we name the notebook `part_ii_inference.ipynb` to match the other two? JP has already created a short link https://pyro.ai/time/part_ii_inference

**Comment by neerajprad** [comment]
> LKJ transform, which seems not possible at the first look, but later turned out to be possible and be much faster than using for-loop

Yes, I was recalling exactly that (tbh this was quite simple in comparison!). 🙂 Thanks for reviewing. We thought that this model is still a bit too complex to get into for first time users. I'll try to pick up this PR at a later date, and will be working on #7 instead in the meantime.

**Pull request closed without merging**
